export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function AuthLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <div>
      
          
        <h1>Hello auth</h1>
          {children}
        
         
      </div>
    )
  }
  